apiVersion: v1
kind: Service
metadata:
  name: rms-ui-service
spec:
  type: NodePort
  selector:
    name: rms-ui-pod
    app: resource-management
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30089